window.AVM = window.AVM || {};

AVM.state = {
  searchTerm: "",
  sortMode: "sr",
  activeFilters: { technology: new Set(), category: new Set(), sample: new Set(), priceBand: new Set() },
  cart: new Set(),
  // "Customer copy" mode: hides B2B cost and margin everywhere a profile is
  // shown or shared (cart drawer, Copy List, Export Excel, Print) so a B2B
  // partner can hand this straight to their own customer without exposing
  // their cost or markup. Off by default — resets each session on purpose,
  // so it's never accidentally left on for the next person using this
  // browser to view their own internal numbers.
  customerView: false,
  // A manually-entered discounted price for the customer copy — B2C rates
  // never get the B2B bulk-value discount, so this is the only way to show
  // a customer a lower number: whoever's building the profile types one in
  // (Make My Profile → Customer copy), and every customer-facing surface
  // (cart drawer, Print Profile, Copy List, Export Excel) then shows the
  // original B2C value alongside it instead of swapping it outright. Kept
  // in rupees (not a %) since it's a one-off negotiated price, not a tiered
  // rule like the B2B discount. null means no discount is set. Persisted
  // alongside the cart (see profile.js) so it survives a reload and carries
  // into Print Profile, but — like the cart itself, and unlike
  // `customerView` above — isn't reset on purpose each session.
  discountedPrice: null,
  currentPage: 1,
  pageSize: (AVM.CONFIG && AVM.CONFIG.DEFAULT_PAGE_SIZE) || 25,
};

(function () {
  // Embedded verbatim from data/*.json — this file is the runtime copy; the JSON
  // files remain the canonical/readable source (and the intended fetch() targets
  // once a real API exists). Duplicated here because file:// blocks fetch().
  const TECHNOLOGIES = [
  { "id": "photometry", "label": "Photometry", "fg": "#0B3E66", "bd": "#1E63B4", "bg": "#DDEAF7" },
  { "id": "eclia", "label": "E.C.L.I.A", "fg": "#0E2238", "bd": "#2C4863", "bg": "#E1E7EC" },
  { "id": "hplc", "label": "H.P.L.C", "fg": "#7A4E14", "bd": "#B96E1D", "bg": "#FBEAD3" },
  { "id": "immunoturbidimetry", "label": "Immunoturbidimetry", "fg": "#5E2E4B", "bd": "#8C466E", "bg": "#F3E1EC" },
  { "id": "hematology", "label": "Hematology", "fg": "#7A3223", "bd": "#B44637", "bg": "#F5DFD9" },
  { "id": "microscopy", "label": "Microscopy", "fg": "#1F4260", "bd": "#3C6E96", "bg": "#DCE9F3" }
];

  const SAMPLES = [
  { "id": "serum", "label": "Serum" },
  { "id": "fluoride", "label": "Fluoride" },
  { "id": "edta", "label": "EDTA" },
  { "id": "urine", "label": "Urine" }
];

  const CATEGORIES = [
  {
    "id": "diabetes",
    "label": "Diabetes"
  },
  {
    "id": "liver-function",
    "label": "Liver Function"
  },
  {
    "id": "kidney-function",
    "label": "Kidney Function"
  },
  {
    "id": "lipid-profile",
    "label": "Lipid Profile"
  },
  {
    "id": "thyroid",
    "label": "Thyroid"
  },
  {
    "id": "iron-studies",
    "label": "Iron Studies"
  },
  {
    "id": "vitamins",
    "label": "Vitamins"
  },
  {
    "id": "cardiac",
    "label": "Cardiac"
  },
  {
    "id": "drug-monitoring",
    "label": "Therapeutic Drug Monitoring"
  },
  {
    "id": "reproductive-hormones",
    "label": "Reproductive & Endocrine Hormones"
  },
  {
    "id": "pregnancy",
    "label": "Pregnancy"
  },
  {
    "id": "tumor-markers",
    "label": "Tumor Markers"
  },
  {
    "id": "infectious-disease",
    "label": "Infectious Disease Serology"
  },
  {
    "id": "autoimmune",
    "label": "Autoimmune"
  },
  {
    "id": "bone-metabolism",
    "label": "Bone Metabolism"
  },
  {
    "id": "pituitary-growth",
    "label": "Pituitary & Growth"
  },
  {
    "id": "allergy-immunology",
    "label": "Allergy & Immunology"
  },
  {
    "id": "general-biochemistry",
    "label": "General Biochemistry"
  },
  {
    "id": "hematology",
    "label": "Hematology"
  },
  {
    "id": "urine",
    "label": "Urine"
  }
];

  const DEPARTMENTS = [
  {
    "id": "biochemistry",
    "label": "Biochemistry"
  },
  {
    "id": "immunoassay",
    "label": "Immunoassay / Serology"
  },
  {
    "id": "hematology",
    "label": "Hematology"
  },
  {
    "id": "clinical-pathology",
    "label": "Clinical Pathology"
  }
];

  const TESTS_WRAPPED = {
  "_note": "container, sampleVolume, and tat are intentionally left null — they need to be confirmed against actual AVM Labs SOPs before use; category/department are business/menu groupings, not clinical guidance.",
  "tests": [
    {
      "sr": 1,
      "code": "ALKP",
      "name": "Alkaline Phosphatase",
      "aliases": ["ALP","Alk Phos"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 1,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 2,
      "code": "BILD",
      "name": "Bilirubin - Direct",
      "aliases": ["Direct Bilirubin","Conjugated Bilirubin"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 2,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 3,
      "code": "BILT",
      "name": "Bilirubin - Total",
      "aliases": ["Total Bilirubin","TBIL"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 3,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 4,
      "code": "BUN",
      "name": "Blood Urea Nitrogen (BUN)",
      "aliases": ["Urea Nitrogen","Blood Urea Nitrogen Test"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "kidney-function",
      "departmentId": "biochemistry",
      "displayOrder": 4,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 5,
      "code": "CALC",
      "name": "Calcium",
      "aliases": ["Serum Calcium","Ca"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "general-biochemistry",
      "departmentId": "biochemistry",
      "displayOrder": 5,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 6,
      "code": "CHOL",
      "name": "Total Cholesterol",
      "aliases": ["Cholesterol","TC"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 6,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 7,
      "code": "CRP",
      "name": "C-Reactive Protein (CRP)",
      "aliases": ["CRP","Quantitative CRP"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "general-biochemistry",
      "departmentId": "biochemistry",
      "displayOrder": 7,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 8,
      "code": "FBS",
      "name": "Fasting Blood Sugar",
      "aliases": ["Fasting Glucose","FBS"],
      "techId": "photometry",
      "sampleId": "fluoride",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "diabetes",
      "departmentId": "biochemistry",
      "displayOrder": 8,
      "fastingRequired": true,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 9,
      "code": "GGT",
      "name": "Gamma Glutamyl Transferase (GGT)",
      "aliases": ["GGT","Gamma GT"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 9,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 10,
      "code": "HCHO",
      "name": "HDL Cholesterol - Direct",
      "aliases": ["HDL","Good Cholesterol"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 10,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 11,
      "code": "IRON",
      "name": "Iron",
      "aliases": ["Serum Iron","Fe"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "iron-studies",
      "departmentId": "biochemistry",
      "displayOrder": 11,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 12,
      "code": "LDL",
      "name": "LDL Cholesterol - Direct",
      "aliases": ["LDL","Bad Cholesterol"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 12,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 13,
      "code": "PHOS",
      "name": "Phosphorous",
      "aliases": ["Serum Phosphorus","Phosphate"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 200,
      "categoryId": "general-biochemistry",
      "departmentId": "biochemistry",
      "displayOrder": 13,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 14,
      "code": "PPBS",
      "name": "Postprandial Blood Sugar",
      "aliases": ["PP Blood Sugar","PPBS"],
      "techId": "photometry",
      "sampleId": "fluoride",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "diabetes",
      "departmentId": "biochemistry",
      "displayOrder": 14,
      "fastingRequired": true,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 15,
      "code": "PROT",
      "name": "Protein - Total",
      "aliases": ["Total Protein","Serum Protein"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 15,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 16,
      "code": "RBS",
      "name": "Random Blood Sugar",
      "aliases": ["Random Glucose","RBS"],
      "techId": "photometry",
      "sampleId": "fluoride",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "diabetes",
      "departmentId": "biochemistry",
      "displayOrder": 16,
      "fastingRequired": false,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 17,
      "code": "SALB",
      "name": "Albumin - Serum",
      "aliases": ["Serum Albumin","Albumin"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 17,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 18,
      "code": "SCRE",
      "name": "Serum Creatinine",
      "aliases": ["Creatinine","Cr"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "kidney-function",
      "departmentId": "biochemistry",
      "displayOrder": 18,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 19,
      "code": "SGOT",
      "name": "Aspartate Aminotransferase (SGOT)",
      "aliases": ["AST","SGOT"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 19,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 20,
      "code": "SGPT",
      "name": "Alanine Transaminase (SGPT)",
      "aliases": ["ALT","SGPT"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "liver-function",
      "departmentId": "biochemistry",
      "displayOrder": 20,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 21,
      "code": "TRIG",
      "name": "Triglycerides",
      "aliases": ["TG","Serum Triglycerides"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 21,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 22,
      "code": "UREA",
      "name": "Blood Urea",
      "aliases": ["Urea","Blood Urea Test"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "kidney-function",
      "departmentId": "biochemistry",
      "displayOrder": 22,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 23,
      "code": "URIC",
      "name": "Uric Acid",
      "aliases": ["Serum Uric Acid","UA"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 40,
      "b2c": 100,
      "categoryId": "kidney-function",
      "departmentId": "biochemistry",
      "displayOrder": 23,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 24,
      "code": "AMYL",
      "name": "Amylase",
      "aliases": ["Serum Amylase","AMY"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 45,
      "b2c": 200,
      "categoryId": "general-biochemistry",
      "departmentId": "biochemistry",
      "displayOrder": 24,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 25,
      "code": "A1c",
      "name": "HbA1c",
      "aliases": ["Glycated Hemoglobin","HbA1c"],
      "techId": "hplc",
      "sampleId": "edta",
      "b2b": 70,
      "b2c": 300,
      "categoryId": "diabetes",
      "departmentId": "biochemistry",
      "displayOrder": 25,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 26,
      "code": "TT3",
      "name": "Total T3",
      "aliases": ["Triiodothyronine","T3"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 20,
      "b2c": 100,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 26,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 27,
      "code": "TT4",
      "name": "Total T4",
      "aliases": ["Thyroxine","T4"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 20,
      "b2c": 100,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 27,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 28,
      "code": "UTSH",
      "name": "Thyroid-Stimulating Hormone.",
      "aliases": ["TSH","Thyrotropin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 20,
      "b2c": 100,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 28,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 29,
      "code": "FT3",
      "name": "Free T3",
      "aliases": ["Free Triiodothyronine","FT3"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 30,
      "b2c": 100,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 29,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 30,
      "code": "FT4",
      "name": "Free T4",
      "aliases": ["Free Thyroxine","FT4"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 30,
      "b2c": 100,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 30,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 31,
      "code": "LASE",
      "name": "Lipase",
      "aliases": ["Serum Lipase","LPS"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 75,
      "b2c": 300,
      "categoryId": "general-biochemistry",
      "departmentId": "immunoassay",
      "displayOrder": 31,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 32,
      "code": "VB12",
      "name": "VitaminB12",
      "aliases": ["Cobalamin","Vitamin B12"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 80,
      "b2c": 400,
      "categoryId": "vitamins",
      "departmentId": "immunoassay",
      "displayOrder": 32,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 33,
      "code": "SAG",
      "name": "Hepatitis B Surface Antigen (HBsAg)",
      "aliases": ["HBsAg","Hepatitis B Surface Antigen"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 85,
      "b2c": 200,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 33,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 34,
      "code": "FSH",
      "name": "Follicle-Stimulating Hormone.",
      "aliases": ["FSH","Follitropin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 90,
      "b2c": 250,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 34,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 35,
      "code": "LH",
      "name": "Luteinizing Hormone",
      "aliases": ["LH","Lutropin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 90,
      "b2c": 250,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 35,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 36,
      "code": "PRL",
      "name": "Prolactin",
      "aliases": ["PRL","Lactogenic Hormone"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 90,
      "b2c": 250,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 36,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 37,
      "code": "TPSA",
      "name": "Total PSA",
      "aliases": ["Prostate-Specific Antigen","PSA"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 90,
      "b2c": 300,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 37,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 38,
      "code": "E2",
      "name": "Estradiol",
      "aliases": ["E2","Oestradiol"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 95,
      "b2c": 300,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 38,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 39,
      "code": "BHCG",
      "name": "Total βHCG",
      "aliases": ["Beta hCG","Pregnancy Hormone Test"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 100,
      "b2c": 300,
      "categoryId": "pregnancy",
      "departmentId": "immunoassay",
      "displayOrder": 39,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 40,
      "code": "HIV",
      "name": "HIV Ab/Ag Combo",
      "aliases": ["HIV Test","HIV 1 & 2 Antibody-Antigen"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 105,
      "b2c": 400,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 40,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 41,
      "code": "VITDT",
      "name": "25-OH Vitamin D Total",
      "aliases": ["Vitamin D","25-Hydroxyvitamin D"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 105,
      "b2c": 400,
      "categoryId": "vitamins",
      "departmentId": "immunoassay",
      "displayOrder": 41,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 42,
      "code": "CMV_G",
      "name": "CMV IgG",
      "aliases": ["Cytomegalovirus IgG","CMV Antibody IgG"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 42,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 43,
      "code": "CMV_M",
      "name": "CMV IgM",
      "aliases": ["Cytomegalovirus IgM","CMV Antibody IgM"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 43,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 44,
      "code": "HSV1G",
      "name": "HSV-1 IgG",
      "aliases": ["Herpes Simplex Virus 1 IgG","HSV1 Antibody"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 44,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 45,
      "code": "HSV2G",
      "name": "HSV-2 IgG",
      "aliases": ["Herpes Simplex Virus 2 IgG","HSV2 Antibody"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 45,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 46,
      "code": "PRGE",
      "name": "Progesterone",
      "aliases": ["P4","Serum Progesterone"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 46,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 47,
      "code": "RBV_G",
      "name": "Rubella IgG",
      "aliases": ["German Measles IgG","Rubella Antibody IgG"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 47,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 48,
      "code": "RBV_M",
      "name": "Rubella IgM",
      "aliases": ["German Measles IgM","Rubella Antibody IgM"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 48,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 49,
      "code": "TXV_G",
      "name": "Toxo IgG",
      "aliases": ["Toxoplasma IgG","Toxoplasmosis Antibody IgG"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 49,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 50,
      "code": "TXV_M",
      "name": "Toxo IgM",
      "aliases": ["Toxoplasma IgM","Toxoplasmosis Antibody IgM"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 110,
      "b2c": 350,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 50,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 51,
      "code": "AHCV",
      "name": "Anti Hepatitis C Virus Total",
      "aliases": ["HCV Antibody","Hepatitis C Test"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 115,
      "b2c": 600,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 51,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 52,
      "code": "TESTO",
      "name": "Testosterone",
      "aliases": ["Total Testosterone","T"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 115,
      "b2c": 300,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 52,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 53,
      "code": "FERR",
      "name": "Ferritin",
      "aliases": ["Serum Ferritin","Iron Storage Test"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 120,
      "b2c": 300,
      "categoryId": "iron-studies",
      "departmentId": "immunoassay",
      "displayOrder": 53,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 54,
      "code": "CA125",
      "name": "CA125",
      "aliases": ["Cancer Antigen 125","Ovarian Tumor Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 125,
      "b2c": 550,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 54,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 55,
      "code": "CEA",
      "name": "Carcinoembryonic Antigen",
      "aliases": ["CEA","Tumor Marker CEA"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 125,
      "b2c": 550,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 55,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 56,
      "code": "INSFA",
      "name": "Insulin",
      "aliases": ["Fasting Insulin","Serum Insulin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 125,
      "b2c": 300,
      "categoryId": "diabetes",
      "departmentId": "immunoassay",
      "displayOrder": 56,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 57,
      "code": "AFP",
      "name": "Alpha-Fetoprotein.",
      "aliases": ["AFP","Tumor Marker AFP"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 130,
      "b2c": 550,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 57,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 58,
      "code": "FPSA",
      "name": "Free PSA",
      "aliases": ["Free Prostate-Specific Antigen","fPSA"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 130,
      "b2c": 550,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 58,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 59,
      "code": "SYPHI",
      "name": "Syphilis",
      "aliases": ["Syphilis Test","Treponema pallidum Antibody"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 130,
      "b2c": 550,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 59,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 60,
      "code": "TIGE",
      "name": "Immunoglobulin E.",
      "aliases": ["IgE","Total IgE"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 130,
      "b2c": 300,
      "categoryId": "allergy-immunology",
      "departmentId": "immunoassay",
      "displayOrder": 60,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 61,
      "code": "CA153",
      "name": "CA15-3",
      "aliases": ["Cancer Antigen 15-3","Breast Tumor Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 140,
      "b2c": 500,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 61,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 62,
      "code": "CA199",
      "name": "CA19-9",
      "aliases": ["Cancer Antigen 19-9","Pancreatic Tumor Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 140,
      "b2c": 500,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 62,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 63,
      "code": "CORT",
      "name": "Cortisol",
      "aliases": ["Serum Cortisol","Hydrocortisone"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 140,
      "b2c": 450,
      "categoryId": "pituitary-growth",
      "departmentId": "immunoassay",
      "displayOrder": 63,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 64,
      "code": "CPEP",
      "name": "C-Peptide",
      "aliases": ["Connecting Peptide","C-Peptide Insulin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 140,
      "b2c": 500,
      "categoryId": "diabetes",
      "departmentId": "immunoassay",
      "displayOrder": 64,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 65,
      "code": "ATG",
      "name": "Anti-Thyroglobulin Antibody",
      "aliases": ["Anti-Tg","Thyroglobulin Antibody"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 160,
      "b2c": 600,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 65,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 66,
      "code": "DHEAS",
      "name": "Dehydroepiandrosterone Sulfate (DHEA-S)",
      "aliases": ["DHEA-S","DHEA Sulfate"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 160,
      "b2c": 600,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 66,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 67,
      "code": "HBCT",
      "name": "Anti-Hepatitis B Core Antibody",
      "aliases": ["Anti-HBc","HBcAb"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 160,
      "b2c": 600,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 67,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 68,
      "code": "HBST",
      "name": "Anti-Hepatitis B Surface Antibody",
      "aliases": ["Anti-HBs","HBsAb"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 160,
      "b2c": 600,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 68,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 69,
      "code": "FOLI",
      "name": "Folic Acid.",
      "aliases": ["Vitamin B9","Folate"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 165,
      "b2c": 450,
      "categoryId": "vitamins",
      "departmentId": "immunoassay",
      "displayOrder": 69,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 70,
      "code": "AHBE",
      "name": "Anti-Hepatitis B e Antibody.",
      "aliases": ["Anti-HBe","HBeAb"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 170,
      "b2c": 450,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 70,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 71,
      "code": "CKMB",
      "name": "Creatine Kinase–Myocardial Band (CK-MB)",
      "aliases": ["CK-MB","Cardiac Enzyme Test"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 170,
      "b2c": 450,
      "categoryId": "cardiac",
      "departmentId": "immunoassay",
      "displayOrder": 71,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 72,
      "code": "EAG",
      "name": "Hepatitis B e Antigen (HBeAg)",
      "aliases": ["HBeAg","Hepatitis B e Antigen"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 170,
      "b2c": 450,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 72,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 73,
      "code": "FBHCG",
      "name": "Free β-HCG",
      "aliases": ["Free Beta hCG","fBHCG"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 170,
      "b2c": 450,
      "categoryId": "pregnancy",
      "departmentId": "immunoassay",
      "displayOrder": 73,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 74,
      "code": "PAPPA",
      "name": "PAPP-A",
      "aliases": ["Pregnancy-Associated Plasma Protein A","First Trimester Screening Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 170,
      "b2c": 450,
      "categoryId": "pregnancy",
      "departmentId": "immunoassay",
      "displayOrder": 74,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 75,
      "code": "HGH",
      "name": "Growth Hormone",
      "aliases": ["Human Growth Hormone","Somatotropin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 180,
      "b2c": 450,
      "categoryId": "pituitary-growth",
      "departmentId": "immunoassay",
      "displayOrder": 75,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 76,
      "code": "MYOG",
      "name": "Myoglobin",
      "aliases": ["Serum Myoglobin","Muscle Protein Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 180,
      "b2c": 500,
      "categoryId": "cardiac",
      "departmentId": "immunoassay",
      "displayOrder": 76,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 77,
      "code": "AMA",
      "name": "Anti-TPO",
      "aliases": ["Thyroid Peroxidase Antibody","TPO Antibody"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 190,
      "b2c": 500,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 77,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 78,
      "code": "SHBG",
      "name": "Sex Hormone-Binding Globulin (SHBG)",
      "aliases": ["SHBG","Sex Hormone Binding Globulin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 190,
      "b2c": 500,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 78,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 79,
      "code": "DIGOX",
      "name": "Digoxin",
      "aliases": ["Digoxin Level","Cardiac Drug Monitoring"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 200,
      "b2c": 550,
      "categoryId": "drug-monitoring",
      "departmentId": "immunoassay",
      "displayOrder": 79,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 80,
      "code": "HSTNI",
      "name": "High-Sensitivity Cardiac Troponin I (hs-cTnI)",
      "aliases": ["Troponin I","Cardiac Troponin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 200,
      "b2c": 600,
      "categoryId": "cardiac",
      "departmentId": "immunoassay",
      "displayOrder": 80,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 81,
      "code": "CALCT",
      "name": "Calcitonin",
      "aliases": ["Serum Calcitonin","Thyrocalcitonin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 210,
      "b2c": 600,
      "categoryId": "bone-metabolism",
      "departmentId": "immunoassay",
      "displayOrder": 81,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 82,
      "code": "ACCP",
      "name": "Anti-Centromeres IgG",
      "aliases": ["Anti-Centromere Antibody","ACA"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 215,
      "b2c": 650,
      "categoryId": "autoimmune",
      "departmentId": "immunoassay",
      "displayOrder": 82,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 83,
      "code": "NPBNP",
      "name": "NT-proBNP",
      "aliases": ["N-terminal proBNP","Heart Failure Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 220,
      "b2c": 650,
      "categoryId": "cardiac",
      "departmentId": "immunoassay",
      "displayOrder": 83,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 84,
      "code": "P1NP",
      "name": "Total P1NP",
      "aliases": ["Procollagen Type 1 N-Terminal Propeptide","Bone Formation Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 220,
      "b2c": 650,
      "categoryId": "bone-metabolism",
      "departmentId": "immunoassay",
      "displayOrder": 84,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 85,
      "code": "PTH",
      "name": "Intact PTH",
      "aliases": ["Parathyroid Hormone","PTH"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 220,
      "b2c": 650,
      "categoryId": "bone-metabolism",
      "departmentId": "immunoassay",
      "displayOrder": 85,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 86,
      "code": "TRAB",
      "name": "Thyrotropin Receptor Antibodies (TRAb)",
      "aliases": ["TSH Receptor Antibody","TRAb"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 220,
      "b2c": 650,
      "categoryId": "thyroid",
      "departmentId": "immunoassay",
      "displayOrder": 86,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 87,
      "code": "HBCM",
      "name": "Anti-Hepatitis A Virus IGM",
      "aliases": ["HAV IgM","Hepatitis A Antibody IgM"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 230,
      "b2c": 700,
      "categoryId": "infectious-disease",
      "departmentId": "immunoassay",
      "displayOrder": 87,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 88,
      "code": "ACTH",
      "name": "Adrenocorticotropic Hormone (ACTH)",
      "aliases": ["ACTH","Corticotropin"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 240,
      "b2c": 700,
      "categoryId": "pituitary-growth",
      "departmentId": "immunoassay",
      "displayOrder": 88,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 89,
      "code": "INFG1",
      "name": "Insulin-like Growth Factor I (IGF-I)",
      "aliases": ["IGF-1","Somatomedin C"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 240,
      "b2c": 750,
      "categoryId": "pituitary-growth",
      "departmentId": "immunoassay",
      "displayOrder": 89,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 90,
      "code": "AMH",
      "name": "Anti-Müllerian Hormone (AMH)",
      "aliases": ["AMH","Ovarian Reserve Test"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 250,
      "b2c": 750,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 90,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 91,
      "code": "NSE",
      "name": "Neuron-Specific Enolase (NSE)",
      "aliases": ["NSE","Neuroendocrine Tumor Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 250,
      "b2c": 750,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 91,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 92,
      "code": "PGRP",
      "name": "Pro–Gastrin-Releasing Peptide (ProGRP)",
      "aliases": ["ProGRP","Lung Cancer Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 250,
      "b2c": 750,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 92,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 93,
      "code": "CA72-4",
      "name": "Cancer Antigen 72-4 (CA72-4)",
      "aliases": ["CA 72-4","Gastric Tumor Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 270,
      "b2c": 650,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 93,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 94,
      "code": "CYFRA",
      "name": "Cytokeratin 19 Fragment 21-1 (CYFRA21-1)",
      "aliases": ["CYFRA 21-1","Lung Cancer Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 270,
      "b2c": 650,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 94,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 95,
      "code": "ANDR",
      "name": "Androstenedione",
      "aliases": ["Serum Androstenedione","Andro"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 300,
      "b2c": 750,
      "categoryId": "reproductive-hormones",
      "departmentId": "immunoassay",
      "displayOrder": 95,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 96,
      "code": "ITRL6",
      "name": "Interleukin-6 (IL-6)",
      "aliases": ["IL-6","Inflammatory Cytokine"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 310,
      "b2c": 750,
      "categoryId": "allergy-immunology",
      "departmentId": "immunoassay",
      "displayOrder": 96,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 97,
      "code": "HE4",
      "name": "Human Epididymis Protein 4. (HE4)",
      "aliases": ["HE4","Ovarian Cancer Marker"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 330,
      "b2c": 850,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 97,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 98,
      "code": "TACRO",
      "name": "Tacrolimus",
      "aliases": ["FK506","Tacrolimus Level"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 380,
      "b2c": 950,
      "categoryId": "drug-monitoring",
      "departmentId": "immunoassay",
      "displayOrder": 98,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 99,
      "code": "PIVKA",
      "name": "Protein Induced by Vitamin K Absence or Antagonist-II (PIVKA-Ⅱ)",
      "aliases": ["PIVKA-II","DCP"],
      "techId": "eclia",
      "sampleId": "serum",
      "b2b": 490,
      "b2c": 1300,
      "categoryId": "tumor-markers",
      "departmentId": "immunoassay",
      "displayOrder": 99,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 100,
      "code": "TIBC",
      "name": "Total Iron Binding Capacity (TIBC)",
      "aliases": ["TIBC","Iron Binding Capacity"],
      "techId": "photometry",
      "sampleId": "serum",
      "b2b": 50,
      "b2c": 200,
      "categoryId": "iron-studies",
      "departmentId": "biochemistry",
      "displayOrder": 100,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 101,
      "code": "CUA",
      "name": "Complete Urine Analysis",
      "aliases": ["Urine Routine","Urinalysis"],
      "techId": "microscopy",
      "sampleId": "urine",
      "b2b": 100,
      "b2c": 300,
      "categoryId": "urine",
      "departmentId": "clinical-pathology",
      "displayOrder": 101,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 102,
      "code": "LPA",
      "name": "Lipoprotein (a)",
      "aliases": ["Lp(a)","Lipoprotein a"],
      "techId": "immunoturbidimetry",
      "sampleId": "serum",
      "b2b": 45,
      "b2c": 200,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 102,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 103,
      "code": "APOA",
      "name": "Apolipoprotein - A1",
      "aliases": ["Apo A1","ApoA-I"],
      "techId": "immunoturbidimetry",
      "sampleId": "serum",
      "b2b": 55,
      "b2c": 200,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 103,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 104,
      "code": "APOB",
      "name": "Apolipoprotein - B",
      "aliases": ["Apo B","ApoB-100"],
      "techId": "immunoturbidimetry",
      "sampleId": "serum",
      "b2b": 55,
      "b2c": 200,
      "categoryId": "lipid-profile",
      "departmentId": "biochemistry",
      "displayOrder": 104,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 105,
      "code": "HSCPRP",
      "name": "High-Sensitivity C-Reactive Protein",
      "aliases": ["hs-CRP","Cardiac CRP"],
      "techId": "immunoturbidimetry",
      "sampleId": "serum",
      "b2b": 60,
      "b2c": 200,
      "categoryId": "general-biochemistry",
      "departmentId": "biochemistry",
      "displayOrder": 105,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    },
    {
      "sr": 106,
      "code": "CBC",
      "name": "Hemogram - 6 Part (Diff)",
      "aliases": ["Complete Blood Count","CBC"],
      "techId": "hematology",
      "sampleId": "edta",
      "b2b": 70,
      "b2c": 300,
      "categoryId": "hematology",
      "departmentId": "hematology",
      "displayOrder": 106,
      "fastingRequired": null,
      "homeCollection": true,
      "reportType": "Digital",
      "container": null,
      "sampleVolume": null,
      "tat": null,
      "active": true
    }
  ]
};
  const TESTS = TESTS_WRAPPED.tests;

  // Common profiles — sourced verbatim from AVMLabs' "Common Profiles" rate
  // card (profile name + test codes). Prices are never stored here: each
  // profile's cost is just the sum of its member tests' own B2B/B2C prices,
  // computed on the fly (see calculations.js totals()) so it always tracks
  // the rate list instead of drifting out of sync with a hardcoded number.
  //
  // calculatedParams: report line items the panel also produces that are
  // NOT separately-priced tests of their own — they're derived/calculated
  // from the priced codes above (e.g. eGFR from Creatinine, VLDL from
  // Triglycerides) and come bundled in at no extra cost. They count toward
  // the panel's total "test" count (per the source rate card) but never
  // toward B2B/B2C/margin.
  const PACKAGES = [
  { "id": "kidney-profile", "name": "Kidney Profile", "categoryId": "kidney-function", "codes": ["BUN", "UREA", "SCRE", "URIC"],
    "calculatedParams": ["BUN / Serum Creatinine Ratio", "eGFR (estimated Glomerular Filtration Rate)"], "active": true },
  { "id": "lipid-profile", "name": "Lipid Profile", "categoryId": "lipid-profile", "codes": ["CHOL", "TRIG", "HCHO", "LDL"],
    "calculatedParams": ["VLDL Cholesterol", "Non-HDL Cholesterol", "TC / HDL Cholesterol Ratio", "LDL / HDL Ratio"], "active": true },
  { "id": "liver-profile", "name": "Liver Profile", "categoryId": "liver-function", "codes": ["ALKP", "BILD", "BILT", "PROT", "SALB", "SGOT", "SGPT", "GGT"],
    "calculatedParams": ["Bilirubin - Indirect", "Globulin", "A:G Ratio"], "active": true },
  { "id": "thyro-5", "name": "Thyro 5", "categoryId": "thyroid", "codes": ["TT3", "TT4", "UTSH", "FT3", "FT4"],
    "calculatedParams": [], "active": true },
  { "id": "iron-profile", "name": "Iron Profile", "categoryId": "iron-studies", "codes": ["IRON", "TIBC"],
    "calculatedParams": [], "active": true },
  { "id": "vitamin-profile", "name": "Vitamin Profile", "categoryId": "vitamins", "codes": ["VB12", "VITDT", "FOLI"],
    "calculatedParams": [], "active": true }
];

  const PARAMETERS_WRAPPED = {
  "_note": "Only populated for tests that are genuinely well-known multi-analyte panels (lipid profile, liver function, kidney function, CBC) — these breakdowns are standard textbook clinical chemistry, not lab-specific. Single-analyte tests are not listed here since the test itself IS the parameter; see js/modules/test-detail.js, which falls back to the test's own name when no breakdown exists.",
  "parameters": [
    { "id": "PAR_CHOL", "name": "Total Cholesterol", "unit": "mg/dL" },
    { "id": "PAR_TRIG", "name": "Triglycerides", "unit": "mg/dL" },
    { "id": "PAR_HDL", "name": "HDL Cholesterol", "unit": "mg/dL" },
    { "id": "PAR_LDL", "name": "LDL Cholesterol", "unit": "mg/dL" },
    { "id": "PAR_VLDL", "name": "VLDL Cholesterol (calculated)", "unit": "mg/dL" },
    { "id": "PAR_CHOL_HDL_RATIO", "name": "Cholesterol / HDL Ratio (calculated)", "unit": "ratio" },

    { "id": "PAR_BILT", "name": "Bilirubin - Total", "unit": "mg/dL" },
    { "id": "PAR_BILD", "name": "Bilirubin - Direct", "unit": "mg/dL" },
    { "id": "PAR_BILI", "name": "Bilirubin - Indirect (calculated)", "unit": "mg/dL" },
    { "id": "PAR_SGOT", "name": "SGOT (AST)", "unit": "U/L" },
    { "id": "PAR_SGPT", "name": "SGPT (ALT)", "unit": "U/L" },
    { "id": "PAR_ALKP", "name": "Alkaline Phosphatase", "unit": "U/L" },
    { "id": "PAR_GGT", "name": "GGT", "unit": "U/L" },
    { "id": "PAR_PROT", "name": "Total Protein", "unit": "g/dL" },
    { "id": "PAR_SALB", "name": "Albumin", "unit": "g/dL" },
    { "id": "PAR_GLOB", "name": "Globulin (calculated)", "unit": "g/dL" },
    { "id": "PAR_AG_RATIO", "name": "A:G Ratio (calculated)", "unit": "ratio" },

    { "id": "PAR_UREA", "name": "Blood Urea", "unit": "mg/dL" },
    { "id": "PAR_BUN", "name": "Blood Urea Nitrogen", "unit": "mg/dL" },
    { "id": "PAR_SCRE", "name": "Serum Creatinine", "unit": "mg/dL" },
    { "id": "PAR_URIC", "name": "Uric Acid", "unit": "mg/dL" },
    { "id": "PAR_BUN_CRE_RATIO", "name": "BUN / Creatinine Ratio (calculated)", "unit": "ratio" },

    { "id": "PAR_WBC", "name": "Total WBC Count", "unit": "/cumm" },
    { "id": "PAR_RBC", "name": "Total RBC Count", "unit": "mill/cumm" },
    { "id": "PAR_HB", "name": "Hemoglobin", "unit": "g/dL" },
    { "id": "PAR_HCT", "name": "Hematocrit (PCV)", "unit": "%" },
    { "id": "PAR_MCV", "name": "MCV", "unit": "fL" },
    { "id": "PAR_MCH", "name": "MCH", "unit": "pg" },
    { "id": "PAR_MCHC", "name": "MCHC", "unit": "g/dL" },
    { "id": "PAR_PLT", "name": "Platelet Count", "unit": "/cumm" },
    { "id": "PAR_NEUT", "name": "Neutrophils", "unit": "%" },
    { "id": "PAR_LYMPH", "name": "Lymphocytes", "unit": "%" },
    { "id": "PAR_MONO", "name": "Monocytes", "unit": "%" },
    { "id": "PAR_EOS", "name": "Eosinophils", "unit": "%" },
    { "id": "PAR_BASO", "name": "Basophils", "unit": "%" }
  ]
};
  const PARAMETERS = PARAMETERS_WRAPPED.parameters;

  const TEST_PARAMETERS_WRAPPED = {
  "_note": "Maps a test code to its parameter breakdown. In this catalog, CBC is the only test that is itself a bundled multi-analyte panel (all other panels — Lipid, Liver, Kidney — are already broken into separate individual line items in tests.json, which is why packages.json groups them instead). Everything else resolves to a single implicit parameter (its own name) in js/modules/test-detail.js.",
  "testParameters": {
    "CBC": [
      "PAR_HB", "PAR_RBC", "PAR_WBC", "PAR_HCT", "PAR_MCV", "PAR_MCH", "PAR_MCHC",
      "PAR_PLT", "PAR_NEUT", "PAR_LYMPH", "PAR_MONO", "PAR_EOS", "PAR_BASO"
    ]
  }
};
  const TEST_PARAMETERS = TEST_PARAMETERS_WRAPPED.testParameters;

  let catalog = null;

  function buildCatalog() {
    const techById = Object.fromEntries(TECHNOLOGIES.map(t => [t.id, t]));
    const sampleById = Object.fromEntries(SAMPLES.map(s => [s.id, s]));
    const categoryById = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));
    const departmentById = Object.fromEntries(DEPARTMENTS.map(d => [d.id, d]));
    const parameterById = Object.fromEntries(PARAMETERS.map(p => [p.id, p]));

    const joined = TESTS.map(t => ({
      ...t,
      tech: techById[t.techId] ? techById[t.techId].label : t.techId,
      sample: sampleById[t.sampleId] ? sampleById[t.sampleId].label : t.sampleId,
      category: categoryById[t.categoryId] ? categoryById[t.categoryId].label : null,
      department: departmentById[t.departmentId] ? departmentById[t.departmentId].label : null,
    }));

    const byCode = Object.fromEntries(joined.map(t => [t.code, t]));
    const techColors = Object.fromEntries(TECHNOLOGIES.map(t => [t.label, t]));
    const packageById = Object.fromEntries(PACKAGES.map(p => [p.id, p]));

    // Reverse-index each conflict group so a test's code resolves straight
    // to the group it belongs to (most tests belong to none).
    const conflictGroupByCode = {};
    (AVM.CONFIG.CONFLICT_GROUPS || []).forEach(group => {
      group.codes.forEach(code => { conflictGroupByCode[code] = group; });
    });

    return {
      tests: joined, byCode,
      technologies: TECHNOLOGIES, techById, techColors,
      samples: SAMPLES, sampleById,
      categories: CATEGORIES, categoryById,
      departments: DEPARTMENTS, departmentById,
      packages: PACKAGES, packageById,
      parameters: PARAMETERS, parameterById,
      testParameters: TEST_PARAMETERS,
      conflictGroupByCode,
    };
  }

  async function loadCatalog() {
    if (!catalog) catalog = buildCatalog();
    return catalog;
  }

  function getCatalog() {
    if (!catalog) throw new Error("Catalog not loaded yet — call loadCatalog() first");
    return catalog;
  }

  // ---- service layer — the seam for a future API swap; every module below
  // reads through these functions rather than touching TESTS/PACKAGES/etc directly ----
  function getTests() { return getCatalog().tests; }
  function getTestByCode(code) { return getCatalog().byCode[code] || null; }
  function getPackages() { return getCatalog().packages; }
  function getCategories() { return getCatalog().categories; }
  function getDepartments() { return getCatalog().departments; }
  function getTechnologies() { return getCatalog().technologies; }
  function getSamples() { return getCatalog().samples; }

  function getParametersForTest(code) {
    const cat = getCatalog();
    const test = cat.byCode[code];
    if (!test) return [];
    const ids = cat.testParameters[code];
    if (ids && ids.length) {
      return ids.map(id => cat.parameterById[id]).filter(Boolean);
    }
    // no breakdown on file — the test itself is the single implicit parameter
    return [{ id: null, name: test.name, unit: null }];
  }

  AVM.data = {
    loadCatalog, getCatalog,
    getTests, getTestByCode, getPackages, getCategories, getDepartments, getTechnologies, getSamples,
    getParametersForTest,
  };
})();
